### ISSUE TITLE
出错 GLOBAL/Start (line 60)             SaveFig(obj,xmin,xmax,'PF');  出错 main (line 26)         Global.Start();

### ISSUE THREAD

**Issue by byq-luo** [tomtkg/Test_Functions_for_Multi-objective_Optimization#1]
出错 GLOBAL/Start (line 60)
            SaveFig(obj,xmin,xmax,'PF');

出错 main (line 26)
        Global.Start();

**Comment by tomtkg** [comment]
thanks for the comment.
Updated and fixed bugs.
